INSERT INTO COURSE_SUBJECT(department_id, course_subject_prefix, course_subject_description)
VALUES
     (0010,	"ACCT",	"Accounting")
    ,(1564,	"AD",	  "AD")
    ,(1160,	"AFLN",	"African Languages")
    ,(1460,	"AFS",	"African Studies")
    ,(0062,	"AFSC",	"Air Force Science")
    ,(0062,	"AJ",	  "Admininstration of Justice")
    ,(2936,	"ART",	"Art")

    ,(2853,	"AVST",	"Aviation Science & Technology")
    ,(2853,	"AWS",  "Airway Science")
    ,(0500,	"BADM",	"Business Admininstration")
    ,(0440,	"BIOL",	"Biology")
    ,(1564,	"CFDV",	"Child & Family" )
    ,(0600,	"CHEM",	"Chemistry")
    ,(1160,	"CHNS",	"Chinese")
    ,(0965,	"CIVE",	"Civil Engineering")
    ,(0965,	"CIVT",	"Civil Engineering Technology")
    ,(2215,	"CLSC",	"Clinical Laboratory Sciences")
    ,(0684,	"CM",	  "Communication")

    ,(0965,	"CMET",	"Computer Engineering Tech")
    ,(1631,	"COE",	"Cooperative Education")
    ,(1631,	"CONS",	"Construction")
    ,(0720,	"CS",	  "Computer Science")
    ,(1564,	"CT",	  "Clothing/Textile")
    ,(1631,	"DRFT",	"Drafting / Design Technology")
    ,(1631,	"DRT",  "Disaster Recovery Testing")
    ,(0965,	"ECE",  "Electrical & Computer Enginering")
    ,(1120,	"ECON",	"Ecomomics")
    ,(0750,	"EDCI",	"Education Curiculum  & Instr.")
    ,(0965,	"ELET",	"Electronics Engr Technology")
    ,(2340,	"EMGT",	"Emergency management")
    ,(0990,	"ENG",	"English")
    ,(0965,	"ENGR",	"Engineering")
    ,(0965,	"ENGT",	"Engineering  Technology")
    ,(0500,	"ENTP",	"ENTP")
    ,(0500,	"ENTR",	"Entrepreneurship")
    ,(0684,	"ERM",  "Entertainment Record Indus Mgmt")
    ,(1564,	"FCS",  "Family Consumer Sciences")

    ,(1120,	"FIN",  "Finance")
    ,(1564,	"FN",	  "Foods & Nutrition")
    ,(2340,	"FORS",	"Forensic Science")
    ,(1160,	"FR",	  "French")
    ,(1738,	"FS",	  "Freshman Seminar")
    ,(1460,	"GEOG",	"Geography")
    ,(0600,	"GEOL",	"Geology")
    ,(1402,	"HED",  "Health Education")
    ,(1460,	"HIST",	"History")
    ,(2340,	"HMSC",	"Homeland Security")

    ,(2380,	"HON",	"Honors College")
    ,(2215,	"HSCR",	"HealthvScience - Core")
    ,(1564,	"HSCS",	"Human Servsv & Consumer Sci")
    ,(2213,	"HSEH",	"Health Science - Envrn. Hlth.")
    ,(2214,	"HSHA",	"Health Science - Health Admin.")
    ,(2215,	"HSHI",	"Health Science and Health Info")
    ,(2214,	"HSRT",	"Health Science - Resp Therp.")
    ,(0010,	"INS",	"Insurance")
    ,(1631,	"ITEC",	"Industrial  Technology")
    ,(1670,	"JOUR",	"Journalism")

    ,(1402,	"KIN",	"Kinesiology")
    ,(1875,	"MATH",	"Mathematics")
    ,(1631,	"MFG",	"Manufacturing")
    ,(0500,	"MGMT",	"Management")
    ,(0500,	"MGSC",	"Management Science")
    ,(0500,	"MIS",  "Management Information Systems")
    ,(0500,	"MKTG",	"Marketing")
    ,(2340,	"MSCI",	"Military Science")
    ,(2853,	"MTMS",	"Maritime Trans Mgmt Security")

    ,(2060,	"MUSA",	"Applied Music")
    ,(2060,	"MUSI",	"Music")
    ,(0062,	"NAVA",	"Naval  Sciences")
    ,(1564,	"NUTR",	"Nutritian")
    ,(2340,	"PA",	  "Public  Affairs")
    ,(1402,	"PE",	  "Physical Education")
    ,(2213,	"PHAR",	"Pharmacy")
    ,(0990,	"PHIL",	"Philosophy")
    ,(2300,	"PHYS",	"Physics")
    ,(2340,	"POLS",	"Politic al Science")

    ,(2380,	"PSY",	"Psychology")
    ,(0990,	"RDG",	"Reading  Education")
    ,(0990,	"READ",	"Reading - No Degree - Development")
    ,(2440,	"REC",	"Recreation")
    ,(2440,	"RTF",	"Radio/ TV/ Film")
    ,(0569,	"SC",	  "Speech Communication")
    ,(2590,	"SOC",  "Sociology")
    ,(2580,	"SOCW",	"Social Work")  
    ,(1160,	"SPAN",	"Spanish") 
    ,(0750,	"SPED",	"Special Education")
    ,(1402,	"SPMT",	"Sport Management")
    ,(2936,	"THC",	"THC")
    ,(2936,	"THEA",	"Theatre")
    ,(2853,	"USCG",	"USCG")
    ,(0990,	"WRIT",	"Writing");